### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by WiteKnite** [goingfine/WinCFScan#7]
When trying to run the program an unhandled exception has occured:

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at WinCFScan.frmMain.updateCFIPListStatusText() in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 507
   at WinCFScan.frmMain.loadCFIPListView() in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 457
   at WinCFScan.frmMain.oneTimeChecks() in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 313
   at WinCFScan.frmMain.timerBase_Tick(Object sender, EventArgs e) in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 191
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by goingfine** [comment]
tnx, it'll fix in next release.
